In [113]:
import pandas as pd
df=pd.read_excel("/content/Data Set 1.xlsx")
df

,SNo.,Emp Code,Unnamed: 2,Name,Unnamed: 4,In Duration (In Hrs),Unnamed: 6,Out Duration( In Hrs),Punch Records
0,1,3,NaN,3,NaN,04:57:00,NaN,00:00:00,"13:10:in(ED),15:43:out(ED),16:00:in(ED),18:08:..."
1,2,5,NaN,5,NaN,19:45:00,NaN,04:39:00,"04:50:in(ED),20:11:out(ED),20:59:in(ED),20:59:..."
2,3,6,NaN,6,NaN,00:00:00,NaN,00:00:00,NaN
3,4,6,NaN,6,NaN,10:54:00,NaN,04:30:00,"04:58:in(ED),04:58:(ED),20:23:out(ED),"
4,5,7,NaN,7,NaN,00:00:00,NaN,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...
85,86,ECS074,NaN,Ilakiyan,NaN,00:00:00,NaN,00:00:00,NaN
86,87,ECS087,NaN,Sakthivel,NaN,00:00:00,NaN,00:00:00,NaN
87,88,T1,NaN,Test Employee 1,NaN,00:00:00,NaN,00:00:00,NaN
88,89,T2,NaN,Test Employee 2,NaN,00:00:00,NaN,00:00:00,NaN
89,90,T3,NaN,Test Employee 3,NaN,00:00:00,NaN,00:00:00,NaN

In [114]:
df = df.drop(["Unnamed: 2","Unnamed: 4","Unnamed: 6"],axis=1)

In [115]:
a=df.dropna()

In [116]:
a

,SNo.,Emp Code,Name,In Duration (In Hrs),Out Duration( In Hrs),Punch Records
0,1,3,3,04:57:00,00:00:00,"13:10:in(ED),15:43:out(ED),16:00:in(ED),18:08:..."
1,2,5,5,19:45:00,04:39:00,"04:50:in(ED),20:11:out(ED),20:59:in(ED),20:59:..."
3,4,6,6,10:54:00,04:30:00,"04:58:in(ED),04:58:(ED),20:23:out(ED),"
5,6,7,7,02:44:00,00:00:00,"10:39:in(ED),13:23:out(ED),"
6,7,8,8,08:48:00,00:00:00,"20:25:in(ED),22:11:out(ED),05:14:in(ED),"
7,8,8,8,02:07:00,00:01:00,"09:52:in(ED),10:41:out(ED),10:58:in(ED),11:59:..."
12,13,13,13,00:00:00,00:00:00,"14:04:in(ED),"
13,14,14,14,01:30:00,00:12:00,"09:16:in(ED),10:44:out(ED),10:59:in(ED),"
14,15,15,15,10:31:00,00:00:00,"14:07:in(ED),00:39:out(ED),"
15,16,15,Sharmila,18:32:00,05:31:00,"03:58:in(ED),19:08:out(ED),04:01:in(ED),"
16,17,16,16,11:10:00,04:43:00,"04:46:in(ED),20:39:out(ED),20:39:(ED),"
18,19,18,18,07:52:00,00:00:00,"20:41:in(ED),21:23:out(ED),22:11:in(ED),04:34:..."
23,24,23,23,18:37:00,00:00:00,"01:31:in(ED),01:59:out(ED),04:38:in(ED),20:08:..."
24,25,24,Bala,20:58:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:08:..."
25,26,25,25,09:02:00,00:00:00,"20:11:in(ED),21:23:out(ED),22:24:in(ED),05:14:..."
26,27,25,25,18:53:00,00:00:00,"01:32:in(ED),01:58:out(ED),04:39:in(ED),04:39:..."
27,28,26,26,18:54:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:29:..."
28,29,27,27,00:00:00,00:00:00,"11:32:in(ED),"
29,30,29,29,08:27:00,00:03:00,"09:26:in(ED),09:59:out(ED),10:05:in(BD),10:31:..."
30,31,30,30,19:16:00,04:43:00,"04:46:in(ED),20:15:out(ED),04:45:in(ED),"
31,32,32,32,18:50:00,00:00:00,"01:31:in(ED),02:00:out(ED),04:38:in(ED),20:21:..."
32,33,34,34,01:15:00,00:00:00,"11:48:in(ED),12:04:out(ED),12:15:in(ED),13:04:..."
33,34,34,34,09:40:00,00:00:00,"13:12:in(ED),18:23:out(ED),18:37:in(ED),22:53:..."
34,35,37,37,19:36:00,00:00:00,"01:59:in(ED),04:41:out(ED),04:42:(BD),20:21:in..."
36,37,43,43,05:15:00,00:00:00,"09:54:in(ED),15:09:out(ED),"
38,39,46,46,18:48:00,00:01:00,"01:33:in(ED),02:00:out(ED),04:38:in(ED),20:21:..."
39,40,48,48,01:25:00,00:00:00,"15:39:in(ED),15:40:(ED),15:40:(ED),17:05:out(ED),"
40,41,50,50,05:16:00,00:00:00,"11:41:in(ED),11:55:out(BD),11:56:(BD),15:23:in..."
42,43,59,59,01:43:00,00:00:00,"11:48:in(ED),12:04:out(ED),12:15:in(ED),13:32:..."
43,44,60,60,03:32:00,00:00:00,"13:25:in(ED),13:25:(ED),13:26:(ED),15:33:out(E..."
44,45,60,60,00:00:00,00:01:00,"16:04:in(BD),16:05:(BD),"
45,46,61,61,04:46:00,00:00:00,"13:23:in(ED),13:23:(ED),13:42:out(ED),14:19:in..."
48,49,64,64,03:50:00,00:10:00,"09:19:in(ED),10:39:out(ED),10:59:in(ED),12:28:..."
49,50,64,64,11:04:00,00:00:00,"13:34:in(ED),18:09:out(ED),18:37:in(ED),00:38:..."
50,51,65,65,02:55:00,00:00:00,"09:58:in(ED),10:39:out(ED),10:59:in(ED),12:53:..."
51,52,66,66,08:27:00,00:46:00,"08:43:in(ED),08:46:(BD),08:47:(BD),09:58:out(E..."
52,53,67,67,01:30:00,00:35:00,"08:54:in(ED),10:39:out(ED),10:59:in(ED),"
53,54,68,68,08:39:00,00:42:00,"08:47:in(ED),08:52:(BD),08:58:out(BD),10:20:in..."
55,56,70,70,01:14:00,00:00:00,"09:44:in(ED),10:39:out(ED),10:59:in(ED),"
56,57,74,74,05:06:00,00:00:00,"13:03:in(ED),13:03:(ED),13:03:(ED),13:18:out(E..."
57,58,75,75,07:01:00,00:00:00,"13:18:in(ED),13:18:(ED),14:19:out(ED),15:02:in..."
60,61,76,76,01:04:00,00:00:00,"20:32:in(ED),20:39:out(ED),20:41:(ED),21:36:in..."
61,62,77,77,07:39:00,00:00:00,"12:29:in(ED),12:42:out(ED),12:43:(ED),12:52:in..."
63,64,78,78,19:04:00,04:48:00,"04:40:in(ED),20:28:out(ED),20:30:(ED),22:12:in..."
64,65,79,79,02:51:00,00:01:00,"12:39:in(BD),12:41:(BD),15:30:out(BD),15:31:(BD),"
65,66,79,79,05:36:00,00:01:00,"12:45:in(ED),15:34:out(ED),15:57:in(ED),18:21:..."
67,68,82,82,05:44:00,00:00:00,"12:48:in(ED),13:36:out(ED),14:10:in(ED),15:37:..."
68,69,84,84,06:33:00,00:00:00,"12:55:in(ED),19:29:out(ED),"
69,70,88,88,08:03:00,00:00:00,"20:28:in(ED),22:12:out(ED),22:46:in(ED),04:32:..."
70,71,89,89,06:55:00,00:00:00,"12:58:in(ED),15:58:out(ED),18:37:in(ED),19:53:..."
72,73,90,90,18:35:00,00:03:00,"01:08:in(BD),01:09:(BD),03:34:out(BD),03:39:(B..."
73,74,91,Kannan,21:22:00,00:00:00,"00:11:in(ED),00:12:(ED),04:00:out(ED),18:59:in..."
74,75,91,91,04:16:00,00:00:00,"13:01:in(ED),15:58:out(ED),17:17:in(ED),"
76,77,99,99,04:43:00,00:00:00,"11:22:in(ED),15:09:out(ED),15:43:in(ED),15:45:..."
77,78,101,101,07:44:00,00:32:00,"09:00:in(ED),10:39:out(ED),10:59:in(ED),12:58:..."

In [117]:
import re
def filter_punch_records(record):
    if pd.isna(record):
        return record

    entries = record.split(',')

    valid_entries = [entry for entry in entries if ('in' in entry or 'out' in entry) and 'BD' not in entry]

    return ','.join(valid_entries)

a['Punch Records'] = a['Punch Records'].apply(filter_punch_records)

<ipython-input-117-588561862cc8>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['Punch Records'] = a['Punch Records'].apply(filter_punch_records)

In [118]:
def check_validity(record):
    if pd.isna(record) or record == '':
        return 'Invalid'

    entries = record.split(',')

    if 'in' in entries[-1]:
        return 'Invalid'
    return 'Valid'
a['Validity'] = a['Punch Records'].apply(check_validity)

<ipython-input-118-dd2c4272bdde>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['Validity'] = a['Punch Records'].apply(check_validity)

In [119]:
a

,SNo.,Emp Code,Name,In Duration (In Hrs),Out Duration( In Hrs),Punch Records,Validity
0,1,3,3,04:57:00,00:00:00,"13:10:in(ED),15:43:out(ED),16:00:in(ED),18:08:...",Valid
1,2,5,5,19:45:00,04:39:00,"04:50:in(ED),20:11:out(ED),20:59:in(ED),21:54:...",Valid
3,4,6,6,10:54:00,04:30:00,"04:58:in(ED),20:23:out(ED)",Valid
5,6,7,7,02:44:00,00:00:00,"10:39:in(ED),13:23:out(ED)",Valid
6,7,8,8,08:48:00,00:00:00,"20:25:in(ED),22:11:out(ED),05:14:in(ED)",Invalid
7,8,8,8,02:07:00,00:01:00,"09:52:in(ED),10:41:out(ED),10:58:in(ED),11:59:...",Valid
12,13,13,13,00:00:00,00:00:00,14:04:in(ED),Invalid
13,14,14,14,01:30:00,00:12:00,"09:16:in(ED),10:44:out(ED),10:59:in(ED)",Invalid
14,15,15,15,10:31:00,00:00:00,"14:07:in(ED),00:39:out(ED)",Valid
15,16,15,Sharmila,18:32:00,05:31:00,"03:58:in(ED),19:08:out(ED),04:01:in(ED)",Invalid
16,17,16,16,11:10:00,04:43:00,"04:46:in(ED),20:39:out(ED)",Valid
18,19,18,18,07:52:00,00:00:00,"20:41:in(ED),21:23:out(ED),22:11:in(ED),04:34:...",Valid
23,24,23,23,18:37:00,00:00:00,"01:31:in(ED),01:59:out(ED),04:38:in(ED),20:08:...",Valid
24,25,24,Bala,20:58:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:08:...",Invalid
25,26,25,25,09:02:00,00:00:00,"20:11:in(ED),21:23:out(ED),22:24:in(ED),05:14:...",Valid
26,27,25,25,18:53:00,00:00:00,"01:32:in(ED),01:58:out(ED),04:39:in(ED),20:26:...",Valid
27,28,26,26,18:54:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:29:...",Valid
28,29,27,27,00:00:00,00:00:00,11:32:in(ED),Invalid
29,30,29,29,08:27:00,00:03:00,"09:26:in(ED),09:59:out(ED),10:31:out(ED),11:18...",Valid
30,31,30,30,19:16:00,04:43:00,"04:46:in(ED),20:15:out(ED),04:45:in(ED)",Invalid
31,32,32,32,18:50:00,00:00:00,"01:31:in(ED),02:00:out(ED),04:38:in(ED),20:21:...",Valid
32,33,34,34,01:15:00,00:00:00,"11:48:in(ED),12:04:out(ED),12:15:in(ED),13:04:...",Valid
33,34,34,34,09:40:00,00:00:00,"13:12:in(ED),18:23:out(ED),18:37:in(ED),22:53:...",Valid
34,35,37,37,19:36:00,00:00:00,"01:59:in(ED),04:41:out(ED),20:21:in(ED),21:36:...",Valid
36,37,43,43,05:15:00,00:00:00,"09:54:in(ED),15:09:out(ED)",Valid
38,39,46,46,18:48:00,00:01:00,"01:33:in(ED),02:00:out(ED),04:38:in(ED),20:21:...",Valid
39,40,48,48,01:25:00,00:00:00,"15:39:in(ED),17:05:out(ED)",Valid
40,41,50,50,05:16:00,00:00:00,"11:41:in(ED),16:58:out(ED)",Valid
42,43,59,59,01:43:00,00:00:00,"11:48:in(ED),12:04:out(ED),12:15:in(ED),13:32:...",Valid
43,44,60,60,03:32:00,00:00:00,"13:25:in(ED),15:33:out(ED),16:58:in(ED)",Invalid
44,45,60,60,00:00:00,00:01:00,,Invalid
45,46,61,61,04:46:00,00:00:00,"13:23:in(ED),13:42:out(ED),14:19:in(ED),15:04:...",Valid
48,49,64,64,03:50:00,00:10:00,"09:19:in(ED),10:39:out(ED),10:59:in(ED),12:28:...",Valid
49,50,64,64,11:04:00,00:00:00,"13:34:in(ED),18:09:out(ED),18:37:in(ED),00:38:...",Valid
50,51,65,65,02:55:00,00:00:00,"09:58:in(ED),10:39:out(ED),10:59:in(ED),12:53:...",Valid
51,52,66,66,08:27:00,00:46:00,"08:43:in(ED),09:58:out(ED),10:24:in(ED),11:14:...",Valid
52,53,67,67,01:30:00,00:35:00,"08:54:in(ED),10:39:out(ED),10:59:in(ED)",Invalid
53,54,68,68,08:39:00,00:42:00,"08:47:in(ED),10:39:out(ED),10:59:in(ED),13:34:...",Invalid
55,56,70,70,01:14:00,00:00:00,"09:44:in(ED),10:39:out(ED),10:59:in(ED)",Invalid
56,57,74,74,05:06:00,00:00:00,"13:03:in(ED),13:18:out(ED),13:41:in(ED),18:09:...",Valid
57,58,75,75,07:01:00,00:00:00,"13:18:in(ED),14:19:out(ED),15:02:in(ED),20:20:...",Valid
60,61,76,76,01:04:00,00:00:00,"20:32:in(ED),20:39:out(ED),21:36:in(ED)",Invalid
61,62,77,77,07:39:00,00:00:00,"12:29:in(ED),12:42:out(ED),12:52:in(ED),13:32:...",Invalid
63,64,78,78,19:04:00,04:48:00,"04:40:in(ED),20:28:out(ED),22:12:in(ED),22:46:...",Invalid
64,65,79,79,02:51:00,00:01:00,,Invalid
65,66,79,79,05:36:00,00:01:00,"12:45:in(ED),15:34:out(ED),15:57:in(ED),18:21:...",Valid
67,68,82,82,05:44:00,00:00:00,"12:48:in(ED),13:36:out(ED),14:10:in(ED),15:37:...",Valid
68,69,84,84,06:33:00,00:00:00,"12:55:in(ED),19:29:out(ED)",Valid
69,70,88,88,08:03:00,00:00:00,"20:28:in(ED),22:12:out(ED),22:46:in(ED),04:32:...",Valid
70,71,89,89,06:55:00,00:00:00,"12:58:in(ED),15:58:out(ED),18:37:in(ED),19:53:...",Valid
72,73,90,90,18:35:00,00:03:00,"09:58:in(ED),10:59:out(ED),13:14:in(ED)",Invalid
73,74,91,Kannan,21:22:00,00:00:00,"00:11:in(ED),04:00:out(ED),18:59:in(ED),21:18:...",Invalid
74,75,91,91,04:16:00,00:00:00,"13:01:in(ED),15:58:out(ED),17:17:in(ED)",Invalid
76,77,99,99,04:43:00,00:00:00,"11:22:in(ED),15:09:out(ED),15:43:in(ED),16:06:...",Valid
77,78,101,101,07:44:00,00:32:00,"09:00:in(ED),10:39:out(ED),10:59:in(ED),12:58:...",Valid

In [120]:
def remove_entries(row):
    if row['Validity'] == 'Valid':
        entries = row['Punch Records'].split(',')

        for i in range(len(entries)):
            if 'in' in entries[i]:
                entries.pop(i)
                break

        for i in range(len(entries)-1, -1, -1):
            if 'out' in entries[i]:
                entries.pop(i)
                break
        return ','.join(entries)
    return row['Punch Records']

a['Punch Records'] = a.apply(remove_entries, axis=1)

<ipython-input-120-e6faac48f66b>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['Punch Records'] = a.apply(remove_entries, axis=1)

In [121]:
a

,SNo.,Emp Code,Name,In Duration (In Hrs),Out Duration( In Hrs),Punch Records,Validity
0,1,3,3,04:57:00,00:00:00,"15:43:out(ED),16:00:in(ED)",Valid
1,2,5,5,19:45:00,04:39:00,"20:11:out(ED),20:59:in(ED),21:54:out(ED),22:11...",Valid
3,4,6,6,10:54:00,04:30:00,,Valid
5,6,7,7,02:44:00,00:00:00,,Valid
6,7,8,8,08:48:00,00:00:00,"20:25:in(ED),22:11:out(ED),05:14:in(ED)",Invalid
7,8,8,8,02:07:00,00:01:00,"10:41:out(ED),10:58:in(ED)",Valid
12,13,13,13,00:00:00,00:00:00,14:04:in(ED),Invalid
13,14,14,14,01:30:00,00:12:00,"09:16:in(ED),10:44:out(ED),10:59:in(ED)",Invalid
14,15,15,15,10:31:00,00:00:00,,Valid
15,16,15,Sharmila,18:32:00,05:31:00,"03:58:in(ED),19:08:out(ED),04:01:in(ED)",Invalid
16,17,16,16,11:10:00,04:43:00,,Valid
18,19,18,18,07:52:00,00:00:00,"21:23:out(ED),22:11:in(ED)",Valid
23,24,23,23,18:37:00,00:00:00,"01:59:out(ED),04:38:in(ED)",Valid
24,25,24,Bala,20:58:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:08:...",Invalid
25,26,25,25,09:02:00,00:00:00,"21:23:out(ED),22:24:in(ED)",Valid
26,27,25,25,18:53:00,00:00:00,"01:58:out(ED),04:39:in(ED)",Valid
27,28,26,26,18:54:00,00:00:00,"00:44:out(ED),04:00:in(ED)",Valid
28,29,27,27,00:00:00,00:00:00,11:32:in(ED),Invalid
29,30,29,29,08:27:00,00:03:00,"09:59:out(ED),10:31:out(ED),11:18:in(ED),11:39...",Valid
30,31,30,30,19:16:00,04:43:00,"04:46:in(ED),20:15:out(ED),04:45:in(ED)",Invalid
31,32,32,32,18:50:00,00:00:00,"02:00:out(ED),04:38:in(ED)",Valid
32,33,34,34,01:15:00,00:00:00,"12:04:out(ED),12:15:in(ED)",Valid
33,34,34,34,09:40:00,00:00:00,"18:23:out(ED),18:37:in(ED)",Valid
34,35,37,37,19:36:00,00:00:00,"04:41:out(ED),20:21:in(ED)",Valid
36,37,43,43,05:15:00,00:00:00,,Valid
38,39,46,46,18:48:00,00:01:00,"02:00:out(ED),04:38:in(ED)",Valid
39,40,48,48,01:25:00,00:00:00,,Valid
40,41,50,50,05:16:00,00:00:00,,Valid
42,43,59,59,01:43:00,00:00:00,"12:04:out(ED),12:15:in(ED)",Valid
43,44,60,60,03:32:00,00:00:00,"13:25:in(ED),15:33:out(ED),16:58:in(ED)",Invalid
44,45,60,60,00:00:00,00:01:00,,Invalid
45,46,61,61,04:46:00,00:00:00,"13:42:out(ED),14:19:in(ED),15:04:out(ED),16:00...",Valid
48,49,64,64,03:50:00,00:10:00,"10:39:out(ED),10:59:in(ED),12:28:out(ED),12:42...",Valid
49,50,64,64,11:04:00,00:00:00,"18:09:out(ED),18:37:in(ED)",Valid
50,51,65,65,02:55:00,00:00:00,"10:39:out(ED),10:59:in(ED)",Valid
51,52,66,66,08:27:00,00:46:00,"09:58:out(ED),10:24:in(ED),11:14:out(ED),12:15...",Valid
52,53,67,67,01:30:00,00:35:00,"08:54:in(ED),10:39:out(ED),10:59:in(ED)",Invalid
53,54,68,68,08:39:00,00:42:00,"08:47:in(ED),10:39:out(ED),10:59:in(ED),13:34:...",Invalid
55,56,70,70,01:14:00,00:00:00,"09:44:in(ED),10:39:out(ED),10:59:in(ED)",Invalid
56,57,74,74,05:06:00,00:00:00,"13:18:out(ED),13:41:in(ED)",Valid
57,58,75,75,07:01:00,00:00:00,"14:19:out(ED),15:02:in(ED)",Valid
60,61,76,76,01:04:00,00:00:00,"20:32:in(ED),20:39:out(ED),21:36:in(ED)",Invalid
61,62,77,77,07:39:00,00:00:00,"12:29:in(ED),12:42:out(ED),12:52:in(ED),13:32:...",Invalid
63,64,78,78,19:04:00,04:48:00,"04:40:in(ED),20:28:out(ED),22:12:in(ED),22:46:...",Invalid
64,65,79,79,02:51:00,00:01:00,,Invalid
65,66,79,79,05:36:00,00:01:00,"15:34:out(ED),15:57:in(ED)",Valid
67,68,82,82,05:44:00,00:00:00,"13:36:out(ED),14:10:in(ED),15:37:out(ED),16:00...",Valid
68,69,84,84,06:33:00,00:00:00,,Valid
69,70,88,88,08:03:00,00:00:00,"22:12:out(ED),22:46:in(ED)",Valid
70,71,89,89,06:55:00,00:00:00,"15:58:out(ED),18:37:in(ED)",Valid
72,73,90,90,18:35:00,00:03:00,"09:58:in(ED),10:59:out(ED),13:14:in(ED)",Invalid
73,74,91,Kannan,21:22:00,00:00:00,"00:11:in(ED),04:00:out(ED),18:59:in(ED),21:18:...",Invalid
74,75,91,91,04:16:00,00:00:00,"13:01:in(ED),15:58:out(ED),17:17:in(ED)",Invalid
76,77,99,99,04:43:00,00:00:00,"15:09:out(ED),15:43:in(ED)",Valid
77,78,101,101,07:44:00,00:32:00,"10:39:out(ED),10:59:in(ED)",Valid

In [122]:
def calculate_break_time(row):
    if row['Validity'] == 'Valid':
        entries = row['Punch Records'].split(',')
        total_break_time = 0
        for i in range(1, len(entries), 2):
            in_time_str = entries[i - 1].split()[-1]
            out_time_str = entries[i].split()[-1]

            in_time_match = re.search(r'\d{2}:\d{2}', in_time_str)
            out_time_match = re.search(r'\d{2}:\d{2}', out_time_str)

            if in_time_match and out_time_match:
                in_time = pd.to_datetime(in_time_match.group(), format='%H:%M')
                out_time = pd.to_datetime(out_time_match.group(), format='%H:%M')
                break_duration = out_time - in_time
                total_break_time += break_duration.total_seconds() / 60
        return total_break_time
    return 0

a['Break Time (minutes)'] = a.apply(calculate_break_time, axis=1)

<ipython-input-122-29157b87f054>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['Break Time (minutes)'] = a.apply(calculate_break_time, axis=1)

In [123]:
a

,SNo.,Emp Code,Name,In Duration (In Hrs),Out Duration( In Hrs),Punch Records,Validity,Break Time (minutes)
0,1,3,3,04:57:00,00:00:00,"15:43:out(ED),16:00:in(ED)",Valid,17.0
1,2,5,5,19:45:00,04:39:00,"20:11:out(ED),20:59:in(ED),21:54:out(ED),22:11...",Valid,65.0
3,4,6,6,10:54:00,04:30:00,,Valid,0.0
5,6,7,7,02:44:00,00:00:00,,Valid,0.0
6,7,8,8,08:48:00,00:00:00,"20:25:in(ED),22:11:out(ED),05:14:in(ED)",Invalid,0.0
7,8,8,8,02:07:00,00:01:00,"10:41:out(ED),10:58:in(ED)",Valid,17.0
12,13,13,13,00:00:00,00:00:00,14:04:in(ED),Invalid,0.0
13,14,14,14,01:30:00,00:12:00,"09:16:in(ED),10:44:out(ED),10:59:in(ED)",Invalid,0.0
14,15,15,15,10:31:00,00:00:00,,Valid,0.0
15,16,15,Sharmila,18:32:00,05:31:00,"03:58:in(ED),19:08:out(ED),04:01:in(ED)",Invalid,0.0
16,17,16,16,11:10:00,04:43:00,,Valid,0.0
18,19,18,18,07:52:00,00:00:00,"21:23:out(ED),22:11:in(ED)",Valid,48.0
23,24,23,23,18:37:00,00:00:00,"01:59:out(ED),04:38:in(ED)",Valid,159.0
24,25,24,Bala,20:58:00,00:00:00,"00:35:in(ED),00:44:out(ED),04:00:in(ED),19:08:...",Invalid,0.0
25,26,25,25,09:02:00,00:00:00,"21:23:out(ED),22:24:in(ED)",Valid,61.0
26,27,25,25,18:53:00,00:00:00,"01:58:out(ED),04:39:in(ED)",Valid,161.0
27,28,26,26,18:54:00,00:00:00,"00:44:out(ED),04:00:in(ED)",Valid,196.0
28,29,27,27,00:00:00,00:00:00,11:32:in(ED),Invalid,0.0
29,30,29,29,08:27:00,00:03:00,"09:59:out(ED),10:31:out(ED),11:18:in(ED),11:39...",Valid,194.0
30,31,30,30,19:16:00,04:43:00,"04:46:in(ED),20:15:out(ED),04:45:in(ED)",Invalid,0.0
31,32,32,32,18:50:00,00:00:00,"02:00:out(ED),04:38:in(ED)",Valid,158.0
32,33,34,34,01:15:00,00:00:00,"12:04:out(ED),12:15:in(ED)",Valid,11.0
33,34,34,34,09:40:00,00:00:00,"18:23:out(ED),18:37:in(ED)",Valid,14.0
34,35,37,37,19:36:00,00:00:00,"04:41:out(ED),20:21:in(ED)",Valid,940.0
36,37,43,43,05:15:00,00:00:00,,Valid,0.0
38,39,46,46,18:48:00,00:01:00,"02:00:out(ED),04:38:in(ED)",Valid,158.0
39,40,48,48,01:25:00,00:00:00,,Valid,0.0
40,41,50,50,05:16:00,00:00:00,,Valid,0.0
42,43,59,59,01:43:00,00:00:00,"12:04:out(ED),12:15:in(ED)",Valid,11.0
43,44,60,60,03:32:00,00:00:00,"13:25:in(ED),15:33:out(ED),16:58:in(ED)",Invalid,0.0
44,45,60,60,00:00:00,00:01:00,,Invalid,0.0
45,46,61,61,04:46:00,00:00:00,"13:42:out(ED),14:19:in(ED),15:04:out(ED),16:00...",Valid,93.0
48,49,64,64,03:50:00,00:10:00,"10:39:out(ED),10:59:in(ED),12:28:out(ED),12:42...",Valid,34.0
49,50,64,64,11:04:00,00:00:00,"18:09:out(ED),18:37:in(ED)",Valid,28.0
50,51,65,65,02:55:00,00:00:00,"10:39:out(ED),10:59:in(ED)",Valid,20.0
51,52,66,66,08:27:00,00:46:00,"09:58:out(ED),10:24:in(ED),11:14:out(ED),12:15...",Valid,94.0
52,53,67,67,01:30:00,00:35:00,"08:54:in(ED),10:39:out(ED),10:59:in(ED)",Invalid,0.0
53,54,68,68,08:39:00,00:42:00,"08:47:in(ED),10:39:out(ED),10:59:in(ED),13:34:...",Invalid,0.0
55,56,70,70,01:14:00,00:00:00,"09:44:in(ED),10:39:out(ED),10:59:in(ED)",Invalid,0.0
56,57,74,74,05:06:00,00:00:00,"13:18:out(ED),13:41:in(ED)",Valid,23.0
57,58,75,75,07:01:00,00:00:00,"14:19:out(ED),15:02:in(ED)",Valid,43.0
60,61,76,76,01:04:00,00:00:00,"20:32:in(ED),20:39:out(ED),21:36:in(ED)",Invalid,0.0
61,62,77,77,07:39:00,00:00:00,"12:29:in(ED),12:42:out(ED),12:52:in(ED),13:32:...",Invalid,0.0
63,64,78,78,19:04:00,04:48:00,"04:40:in(ED),20:28:out(ED),22:12:in(ED),22:46:...",Invalid,0.0
64,65,79,79,02:51:00,00:01:00,,Invalid,0.0
65,66,79,79,05:36:00,00:01:00,"15:34:out(ED),15:57:in(ED)",Valid,23.0
67,68,82,82,05:44:00,00:00:00,"13:36:out(ED),14:10:in(ED),15:37:out(ED),16:00...",Valid,57.0
68,69,84,84,06:33:00,00:00:00,,Valid,0.0
69,70,88,88,08:03:00,00:00:00,"22:12:out(ED),22:46:in(ED)",Valid,34.0
70,71,89,89,06:55:00,00:00:00,"15:58:out(ED),18:37:in(ED)",Valid,159.0
72,73,90,90,18:35:00,00:03:00,"09:58:in(ED),10:59:out(ED),13:14:in(ED)",Invalid,0.0
73,74,91,Kannan,21:22:00,00:00:00,"00:11:in(ED),04:00:out(ED),18:59:in(ED),21:18:...",Invalid,0.0
74,75,91,91,04:16:00,00:00:00,"13:01:in(ED),15:58:out(ED),17:17:in(ED)",Invalid,0.0
76,77,99,99,04:43:00,00:00:00,"15:09:out(ED),15:43:in(ED)",Valid,34.0
77,78,101,101,07:44:00,00:32:00,"10:39:out(ED),10:59:in(ED)",Valid,20.0

In [124]:
a.to_excel('Output.xlsx', index=False)

In [125]:
from google.colab import files
files.download('Output.xlsx')